export const GET_SHOPS_REQUEST = 'GET_SHOPS_REQUEST';
export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';
export const GET_SHOPS_ERROR = 'GET_SHOPS_ERROR';

export const SHOPS_RESET = 'SHOPS_RESET';